version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: integrationTest-rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
        - "5672:5672"
        - "15672:15672"
        - "15692:15692"

  mongo:
    image: mongo
    container_name: integrationTest-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo1A2b3C
    ports:
      - "27017:27017"
    restart: always